Np 9100 auth publication workflow
BIBSYSDEV/nva-identity-service pull request #214
Opened 2022-05-10 11:01 UTC by torarnet

2022-05-10 18:50 UTC, brinxmat requested changes

2022-05-10 18:50 UTC, brinxmat commented on customer/src/main/java/no/unit/nva/customer/update/UpdateCustomerHandler.java
> +    private boolean updatesPublicationWorkflow(CustomerDto currentCustomer, CustomerDto input) {
Perhaps isPublicationWorkflowChange

2022-05-10 20:36 UTC, axthosarouris requested changes

2022-05-10 20:36 UTC, axthosarouris commented on customer/src/test/java/no/unit/nva/customer/update/UpdateCustomerHandlerPublicationWorkflowTest.java
> +        createCustomer = GatewayResponse.fromOutputStream(createOutputStream, CustomerDto.class)
preExistingCustomer

2022-05-10 20:36 UTC, axthosarouris commented on customer/src/test/java/no/unit/nva/customer/update/UpdateCustomerHandlerPublicationWorkflowTest.java
> +        InputStream request = updateRequestWithCorrectAuthorization(updateCustomer,
var

2022-05-11 09:13 UTC, axthosarouris submitted a review, later dismissed

2022-05-12 09:08 UTC, brinxmat approved these changes

2022-05-12 09:09 UTC, axthosarouris approved these changes

2022-05-12 09:11 UTC, merged