adding nvi role to app admin
BIBSYSDEV/nva-identity-service pull request #302
Opened 2023-08-22 11:38 UTC by truhacevkir

2023-08-22 11:45 UTC, ketilaa requested changes
I think you have an unintentional change in the template?

2023-08-22 11:45 UTC, ketilaa commented on template.yaml
> +      Name: !Sub '${ParameterNamePrefix}CognitoAuthenIticationDomain'
This change is probably not intentional?

2023-08-23 07:07 UTC, StigNorland approved these changes

2023-08-23 12:22 UTC, anetteOlli approved these changes

2023-08-24 10:58 UTC, merged