Adding isInactive to Customer API.
BIBSYSDEV/nva-identity-service pull request #320
Opened 2023-12-21 08:58 UTC by EyobSikt

Adding isInactive to Customer API

2023-12-21 09:39 UTC, ketilaa requested changes
Generally, I would have used to non-negating version isActive in the code, but it is not a major thing. I would prefer that you added some more tests though:

- create publication setting inactive to true/false
- update publication setting inactive to true/false

2024-01-22 11:15 UTC, anetteOlli commented
Endret til inactiveFrom som et instant.

2024-01-22 11:18 UTC, anetteOlli commented on customer-testing/src/main/java/no/unit/nva/customer/testing/CustomerDataGenerator.java
> +    public static CustomerDao createSampleActiveCustomerDao() {
Lager en egen for aktiv og en egen for inaktiv kunde. (flere randomCustomerGenerators rundt om kring).

Dette slik at sjekket at rundturen gjennom serialisering får med seg alle verdiene.
Samtidig så vil de fleste logiske operasjoner og sjekker skje på aktive kunder.

å sette inactiveFrom til å være return randomBolea() ? randomInstant() : null vil føre til at tester tryner randomly.

2024-01-25 08:51 UTC, ketilaa requested changes
Ser ut som om du har en test som ikke tester noe. Bør fikses.

2024-01-25 11:16 UTC, anetteOlli commented on customer/src/test/java/no/unit/nva/customer/update/UpdateCustomerHandlerTest.java
> +    void requestToHandlerReturnsCustomerInactiveUpdated() throws InputException, NotFoundException, IOException {
Nice catch. Jeg var lat og refaktorerte til testene kjørte uten å tenke så hardt over hvordan de var skrevet.
Desverre ser jeg det er teknisk gjeld her. Det er flere tester som er skrevet slik. 
Skriver denne over til at det foregår en mockitor.verify. Men vi bør gå igjennom flere eksisterende tester i dette repoet.

2024-01-25 11:24 UTC, anetteOlli commented on customer/src/test/java/no/unit/nva/customer/update/UpdateCustomerHandlerTest.java
> +    void requestToHandlerReturnsCustomerInactiveUpdated() throws InputException, NotFoundException, IOException {
Fikk også lagt på en verify på en annen urelatert test jeg fant. Men det hadde vært bedre om det ble gjort slik som det gjøres i publication-api at det settes opp en "base" og så sjekker man at den klarer rundturen gjennom basen.

2024-01-25 11:27 UTC, ketilaa commented on customer/src/test/java/no/unit/nva/customer/update/UpdateCustomerHandlerTest.java
> +    void requestToHandlerReturnsCustomerInactiveUpdated() throws InputException, NotFoundException, IOException {
Lag en task i backlogen med label "teknisk gjeld", så kan teamet plukke det opp senere.

2024-01-25 11:28 UTC, ketilaa approved these changes

2024-01-25 12:28 UTC, anetteOlli commented on customer/src/test/java/no/unit/nva/customer/update/UpdateCustomerHandlerTest.java
> +    void requestToHandlerReturnsCustomerInactiveUpdated() throws InputException, NotFoundException, IOException {
Task: https://unit.atlassian.net/browse/NP-46077?atlOrigin=eyJpIjoiZGUxMDZlMzE1MTMzNGRiNjgxMzI5NmM1MjRkMTY2NjAiLCJwIjoiaiJ9

2024-01-25 19:43 UTC, brinxmat approved these changes

2024-01-26 14:24 UTC, merged