Np 47873/terms conditions
BIBSYSDEV/nva-identity-service pull request #385
Opened 2024-11-15 14:13 UTC by StigNorland

2024-11-18 13:32 UTC, ketilaa requested changes
As we expect a different behaviour in `UserSelectionUponLoginHandler`, I would like to see a new test `UserSelectionUponLoginHandlerTest#shouldClearUserAttributesAndReturnRestrictedTokenWhenLatestTermsAreNotAccepted()`

2024-11-27 10:47 UTC, ketilaa commented
You are aware that @torbjokv is completing the "return token without access right claims if latest version of terms are not approved"? You are still committing code to this branch, so I think you and @torbjokv need to talk.

2024-11-29 08:40 UTC, ketilaa commented
Build is failing. Re-request review when fixed.

2024-11-29 09:43 UTC, ketilaa approved these changes
Approved given that you fix gradle issue commented.

2024-11-29 09:43 UTC, ketilaa commented on dynamo-client/build.gradle
> +    implementation libs.dynamoDbLocal
testImplementation?

2024-11-29 09:43 UTC, ketilaa commented on user-access-handlers/src/test/java/no/unit/nva/handlers/HandlerTest.java
> +            logger.error("Error inserting role", e);
Good. Get rid of code smells like `e.printStackTrace()`

2024-11-29 09:44 UTC, torbjokv approved these changes
good stuff, lets rethink UserSelectArguments at a later date 👍

2024-11-29 10:13 UTC, merged